name: node js

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        run: Copy-item -Force -Recurse -Verbose "C:\ActionRunners\TransamNodeJSAPIRunner\_work\TransamNodeJSAPI\TransamNodeJSAPI\*" -Destination "C:\www\nodejsapi.transamcarriers.ca\";Remove-Item 'C:\www\nodejsapi.transamcarriers.ca\.git' -Force -Recurse -Verbose;Remove-Item 'C:\www\nodejsapi.transamcarriers.ca\.github' -Force -Recurse -Verbose;cd C:\www\nodejsapi.transamcarriers.ca;npm i;
        
        
        

        

